import type { Metadata } from 'next'
import FormTrending from '@/components/Dashboard/Trending/FormTrending'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <>
        <FormTrending />
    </>
  )
}

export default page