import type { Metadata } from 'next'
import FormPcGames from '@/components/Dashboard/GamesPc/FormPcGames'

export const metadata: Metadata = {
    title: 'Create Dashboard - Reyvin Store',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <div>
      <FormPcGames />
    </div>
  )
}

export default page