import type { Metadata } from 'next'
import FormCarousel from '@/components/Dashboard/Carousel/FormCarousel'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <>
        <FormCarousel />
    </>
  )
}

export default page