import type { Metadata } from 'next'
import PcGamesDashboard from '@/components/Dashboard/GamesPc/PcDashboard'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <div>
      <PcGamesDashboard />
    </div>
  )
}

export default page