import type { Metadata } from 'next'
import CarouselDashboard from '@/components/Dashboard/Carousel/CarouselDashboard'

export const metadata: Metadata = {
    title: 'Carousel Dashboard - Reyvin Store',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <>
        <CarouselDashboard />
    </>
  )
}

export default page