import type { Metadata } from 'next'
import Dashboard from "@/components/Dashboard/Dashboard"

export const metadata: Metadata = {
  title: 'Home Dashboard - Reyvin Store',
  description: 'Generated by create next app',
}

function page() {
  return (
    <>
        <Dashboard />
    </>
  )
}

export default page