import type { Metadata } from 'next'
import MobileGamesDashboard from '@/components/Dashboard/Mobile/MobileDashboard'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <div>
      <MobileGamesDashboard />
    </div>
  )
}

export default page