import type { Metadata } from 'next'
import EditTrendingDashboard from '@/components/Dashboard/Trending/EditFormTrending'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <>
        <EditTrendingDashboard />
    </>
  )
}

export default page