import type { Metadata } from 'next'
import FormMobile from '@/components/Dashboard/Mobile/FormMobile'

export const metadata: Metadata = {
    title: 'Create Dashboard - Reyvin Store',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <div>
      <FormMobile />
    </div>
  )
}

export default page