import type { Metadata } from 'next'
import TrendingDashboard from "@/components/Dashboard/Trending/TrendingDashboard"

export const metadata: Metadata = {
    title: 'Trending Dashboard - Reyvin Store',
    description: 'Generated by create next app',
  }

function page() {
  return (
    <>
        <TrendingDashboard />
    </>
  )
}

export default page